config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :good_to_knows do
    collection do
      get 'search'
    end
  end
  
  get 'pages/home'
  get 'pages/simple_home'
  get 'pages/profile'
  get 'pages/resume'
  get 'pages/return_home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/test'
  get 'pages/projects'
  get 'pages/inDevelopment'

  root 'pages#home'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/good_to_know.rb
class GoodToKnow < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  searchkick #word_start: [:title, :content, :tags]

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/controllers/good_to_knows_controller.rb
class GoodToKnowsController < ApplicationController
  before_action :set_good_to_know, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:new, :edit, :update, :destroy]
  skip_before_action  :verify_authenticity_token

  # GET /good_to_knows
  # GET /good_to_knows.json
  def index
    # @good_to_knows = GoodToKnow.all
    @good_to_knows = GoodToKnow.paginate(:page => params[:page], :per_page => 4)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_to_know }
      format.js
    end
  end

  # GET /good_to_knows/1
  # GET /good_to_knows/1.json
  def show
    @good_to_knows = GoodToKnow.all
    @good_to_know = GoodToKnow.find(params[:id])
    @next_entry = @good_to_know.next
    @previous_entry = @good_to_know.previous
    @related = []
    @relatedTags = @good_to_know.tags.split(/\s*,\s*/)

    @good_to_knows.each do |good_to_know|
      @related << good_to_know if checkRelated(@relatedTags, good_to_know.tags) && good_to_know.id != @good_to_know.id
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_to_know }
      format.js
    end
  end


  def checkRelated(relatedTags, entryTags)
    relatedTags.each do |tag|
      if entryTags =~ /#{tag}/i
        return true
      end
    end
    return false
  end

  def search
    if params[:search].present?
      puts "\n\nTEST 1\n\n"
      @good_to_knows = GoodToKnow.search params[:search], page: params[:page], per_page: 4
    else
      puts "\n\nTEST 2\n\n"
      @good_to_knows = nil
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_to_know }
      format.js
    end
  end

  # GET /good_to_knows/new
  def new
    @good_to_know = GoodToKnow.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_to_know }
      format.js
    end
  end

  # GET /good_to_knows/1/edit
  def edit

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_to_know }
      format.js
    end
  end

  # POST /good_to_knows
  # POST /good_to_knows.json
  def create
    @good_to_know = GoodToKnow.new(good_to_know_params)

    respond_to do |format|
      if @good_to_know.save
        format.html { redirect_to @good_to_know, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @good_to_know }
        format.js
      else
        format.html { render :new }
        format.json { render json: @good_to_know.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /good_to_knows/1
  # PATCH/PUT /good_to_knows/1.json
  def update
    respond_to do |format|
      if @good_to_know.update(good_to_know_params)
        format.html { redirect_to @good_to_know, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @good_to_know }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @good_to_know.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /good_to_knows/1
  # DELETE /good_to_knows/1.json
  def destroy
    @good_to_know.destroy
    respond_to do |format|
      format.html { redirect_to good_to_knows_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good_to_know
      @good_to_know = GoodToKnow.find(params[:id])
    end

    # only allow me to add, edit, and delete things
    def check_auth
      if user_signed_in?
        return true
      else
        redirect_to good_to_knows_path, notice: 'Sorry! You\'re not me!'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_to_know_params
      params.require(:good_to_know).permit(:title, :content, :tags)
    end
end

app/helpers/good_to_knows_helper.rb
module GoodToKnowsHelper
end

app/views/good_to_knows/_edit.html.erb
<%= render 'form' %>

app/views/good_to_knows/_form.html.erb
<script>
  if ($('textarea').length > 0) {
    var data = $('textarea');
    $.each(data, function(i) {
      CKEDITOR.replace(data[i].id);
    });
  }
</script>
<%= form_for(@good_to_know) do |f| %>
  <% if @good_to_know.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good_to_know.errors.count, "error") %> prohibited this good_to_know from being saved:</h2>

      <ul>
      <% @good_to_know.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="">
    <div class="form-group">
      <%= f.label :title, style:'color: #A239CA' %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :content, style:'color: #A239CA' %><br>
      <%= f.text_area :content, class: "ckeditor", style: 'height:600px;'%>
    </div>
    <div class="form-group">
      <%= f.label :tags, "Tags (add/edit tags to make searching easier)", style:'color: #A239CA' %><br>
      <%= f.text_field :tags, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', :class=> "hollow button primary"%>
    </div>
  </div>
<% end %>

app/views/good_to_knows/_index2.html.erb
<%= stylesheet_link_tag "vaultIndex", media: "all" %>
<%#= js_will_paginate @recipes %>

<div class="row align-middle" style="margin-bottom: 15px;">
  <div class="large-8 columns">
    <%= form_tag search_good_to_knows_path, method: :get, :remote => true, id: "mysearch" do %>
      <%= text_field_tag :search, params[:search], class: "", :placeholder => 'Search the Vault' %>
    <% end %>
  </div>
    <div class="large-4 columns" align="right" id="new_butto">
      <%= link_to "New Entry", new_good_to_know_path, :remote => true, :id =>"new_button_link" %>
  </div>
</div>

<div class="row">
  <div style="height: 1px; margin-bottom: 10px"></div>

  <div class="large-4 columns" id="vaultList">
    <% counter = 0 %>
    <div class="row">
    <% @good_to_knows.each do |good_to_know| %>

          <div class="entry large-3 columns" align="center" style="padding: 8px">
            <%= link_to good_to_know_path(good_to_know.id), :class=>'entry_content' do %>
              <%= image_tag "/assets/file_folder.png", :class=>'entry_icon' %>
              <div class="entry_title" align="center"><%=good_to_know.title%></div>
            <% end %>
            <%#= image_tag("/assets/blank_folder.png", :style=>'height: 50px;')%>
            <!-- <%= link_to good_to_know.title, good_to_know_path(good_to_know.id), :remote => true, :class => 'entryLinks' %> -->
          </div>


      <script>
        var content = "";
        my_content = document.getElementById("my_content_<%= counter %>").getAttribute("data-good_to_know");
        if(my_content != "" && my_content != null) {
          document.getElementById("my_content_<%= counter %>").innerHTML = my_content;
        }
      </script>
      <% counter = counter +1 %>

    <% end %>
    </div>
    <%#= will_paginate @good_to_knows %>
    <div style="float:right">
      <%= js_will_paginate @good_to_knows %>
    </div>
  </div>

  <div class="large-8 columns" id="vaultEntry">
    &nbsp
  </div>

  <% counter = 0 %>

</row>

app/views/good_to_knows/_index3.html.erb
<section style="background: white; color: black">
  <div class="row align-center">
    <div class="large-10 columns">

      <h2 align="center">The Vault</h2>
      <div class="row" id="vault_intro" align="center">
        The Vault is a collection of technical knowledge I have picked up over the years and felt the need to document.
        Recently, I have started to use it like a blog. Feel free to peruse and utilize the knowledge!
      </div>

      <div class="row align-middle" style="margin-bottom: 15px;">
       <div class="large-8 columns">
         <%= form_tag search_good_to_knows_path, method: :get, id: "mysearch" do %>
           <%= text_field_tag :search, params[:search], class: "", :placeholder => 'Search the Vault' %>
         <% end %>
       </div>
         <div class="large-4 columns" align="right">
           <% if user_signed_in? %>
             <%= button_to "New Entry", new_good_to_know_path, :method => 'get',  :class =>"hollow button primary", :id =>"new_button" %>
           <% else %>
             <button type="button" id="new_button" class="hollow button primary disabled" disabled>New Entry</button>
           <% end %>
       </div>
      </div>



      <% counter = 0 %>
      <div class="row">
        <% @good_to_knows.each do |good_to_know| %>
          <div class="large-12 columns" style="margin-bottom: 35px; padding: 35px; border: 1px solid #A239CA;">
            <%#= link_to good_to_know_path(good_to_know.id), :class=>'entry_content' do %>

                <div style="color: #086F9C">
                  <div style="float:right">
                    <img src="/assets/vault_icon_1.png" alt="Vault icon" width="50" />
                  </div>
                  <h4><%=good_to_know.title%></h4>
                </div>
                <div>
                  <h6 style="color: #A239CA">Tags: <%=good_to_know.tags%></h6>
                </div>
                <div class="card-user-profile-info" data-good_to_know="<%=h truncate(good_to_know.content, :length => 500, :omission => '...') %>" id="my_content_<%= counter %>"></div>

              <div class="card-user-profile-actions">
                <%= link_to 'Open', good_to_know_path(good_to_know), :class => "thislink card-user-profile-button hollow button secondary" %>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_good_to_know_path(good_to_know), :class => "thislink card-user-profile-button hollow button primary" %>
                <% else %>
                  <button type="button" class="thislink card-user-profile-button hollow button primary disabled" disabled>Edit</button>
                <% end %>

              </div>
            <%# end %>
          </div>

          <script>
            var content = "";
            my_content = document.getElementById("my_content_<%= counter %>").getAttribute("data-good_to_know");
            if(my_content != "" && my_content != null) {
              document.getElementById("my_content_<%= counter %>").innerHTML = my_content;
            }
          </script>
          <% counter = counter +1 %>

        <% end %>
      </div>
      <div align="center" style="margin: 35px 0px; color:black">
        <%= will_paginate @good_to_knows %>
      </div>
    </div>
  </div>
</section>

app/views/good_to_knows/_new.html.erb
<%= render 'form' %>

app/views/good_to_knows/_search.html.erb
<section style="background: white; color: black">
  <div class="row align-center">
    <div class="large-10 columns">

      <h2 align="center">Search the Vault</h2>
      <div class="row" id="vault_intro" align="center">
        The Vault is a collection of technical knowledge I have picked up over the years and felt the need to document.
        Recently, I have started to use it like a blog. Feel free to peruse and utilize the knowledge!
      </div>

      <div class="row align-middle" style="margin-bottom: 15px;">
       <div class="large-8 columns">
         <%= form_tag search_good_to_knows_path, method: :get, id: "mysearch" do %>
           <%= text_field_tag :search, params[:search], class: "", :placeholder => 'Search the Vault' %>
         <% end %>
       </div>
         <div class="large-4 columns" align="right">
           <% if user_signed_in? %>
             <%= button_to "New Entry", new_good_to_know_path, :method => 'get',  :class =>"hollow button primary", :id =>"new_button" %>
           <% else %>
             <button type="button" id="new_button" class="hollow button primary disabled" disabled>New Entry</button>
           <% end %>
       </div>
      </div>



      <% counter = 0 %>
      <div class="row">
        <% @good_to_knows.each do |good_to_know| %>
          <div class="large-12 columns" style="margin-bottom: 35px; padding: 35px; border: 1px solid #A239CA;">
            <%#= link_to good_to_know_path(good_to_know.id), :class=>'entry_content' do %>

                <div style="color: #086F9C">
                  <div style="float:right">
                    <img src="/assets/vault_icon_1.png" alt="Vault icon" width="50" />
                  </div>
                  <h4><%=good_to_know.title%></h4>
                </div>
                <div>
                  <h6 style="color: #A239CA">Tags: <%=good_to_know.tags%></h6>
                </div>
                <div class="card-user-profile-info" data-good_to_know="<%=h truncate(good_to_know.content, :length => 500, :omission => '...') %>" id="my_content_<%= counter %>"></div>

              <div class="card-user-profile-actions">
                <%= link_to 'Open', good_to_know_path(good_to_know), :class => "thislink card-user-profile-button hollow button secondary" %>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_good_to_know_path(good_to_know), :class => "thislink card-user-profile-button hollow button primary" %>
                <% else %>
                  <button type="button" class="thislink card-user-profile-button hollow button primary disabled" disabled>Edit</button>
                <% end %>

              </div>
            <%# end %>
          </div>

          <script>
            var content = "";
            my_content = document.getElementById("my_content_<%= counter %>").getAttribute("data-good_to_know");
            if(my_content != "" && my_content != null) {
              document.getElementById("my_content_<%= counter %>").innerHTML = my_content;
            }
          </script>
          <% counter = counter +1 %>

        <% end %>
      </div>
      <div align="center" style="margin: 35px 0px; color:black">
        <%= will_paginate @good_to_knows %>
      </div>
    </div>
  </div>
</section>

app/views/good_to_knows/_show.html.erb
<script>
var content = "";
  $(document).ready(function(){
    my_content = document.getElementById("my_content").getAttribute("data-good_to_know");
    if(my_content != "" && my_content != null) {
      document.getElementById("my_content").innerHTML = my_content;
    }
  });
</script>
<div style="height: 50px;">&nbsp</div>

<div class="row align-center large-collapse">
  <div class="columns small-1 quick-nav">
    <% if @previous_entry != nil %>
      <%= link_to '<-<br/>'.html_safe + @previous_entry.title, good_to_know_path(@previous_entry), :class => "thislink hollow button primary" %>
    <% else %>
      <button type="button" class="button hollow primary" disabled> <- </button>
    <% end %>
  </div>
	<div class="vault-entry columns small-10">
	  <h4 align="center">
	  		<%=@good_to_know.title %>
	  </h4>
	  <div class="vault-entry-content">
	    	<div data-good_to_know="<%= @good_to_know.content %>" id="my_content"></div>
	  </div>
	  <div class="vault-entry-tags-container">
    	<h5 class="vault-entry-tags-label">Tags</h5>
    	<div class="vault-entry-tags">
        <% @relatedTags.each do |t| %>
          <div class="vault-entry-tag">
            <%= link_to t, search_good_to_knows_path(:search => t), class: 'hollow button warning' %>
          </div>
        <% end %>
    	</div>
	  </div>
	  <div align="right">
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_good_to_know_path(@good_to_know), :class => "thislink hollow button primary" %>
        <%= link_to 'Delete', @good_to_know, method: :delete, data: { confirm: 'Are you sure?'}, :class => "thislink hollow button alert" %>
      <% else %>
        <button type="button" class="hollow button primary disabled" disabled>Edit</button>
        <button type="button" class="hollow button alert disabled" disabled>Delete</button>
      <% end %>
	  </div>
  </div>
  <div class="columns small-1 quick-nav" align="right">
    <% if @next_entry != nil %>
      <%= link_to '-><br/>'.html_safe + @next_entry.title, good_to_know_path(@next_entry), :class => "thislink hollow button primary" %>
    <% else %>
      <button type="button" class="button hollow primary" disabled> -> </button>
    <% end %>
  </div>
</div>

<hr>

<h4 align="center" id="related-entries-title">Related Entries</h4>
<% if @related.length > 0 %>
  <div class="row align-center">
    <% counter = 0 %>
    <% @related.each do |r| %>
        <div class="large-12 columns" style="margin-bottom: 35px; padding: 35px; border: 1px solid #A239CA;">
          <%#= link_to good_to_know_path(good_to_know.id), :class=>'entry_content' do %>

              <div style="color: #086F9C">
                <div style="float:right">
                  <img src="/assets/vault_icon_1.png" alt="Vault icon" width="50" />
                </div>
                <h4><%=r.title%></h4>
              </div>
              <div>
                <h6 style="color: #A239CA">Tags: <%=r.tags%></h6>
              </div>
              <div class="card-user-profile-info" data-good_to_know="<%=h truncate(r.content, :length => 500, :omission => '...') %>" id="my_content_<%= counter %>"></div>

            <div class="card-user-profile-actions">
              <%= link_to 'Open', good_to_know_path(r), :class => "thislink card-user-profile-button hollow button secondary" %>
              <% if user_signed_in? %>
                <%= link_to 'Edit', edit_good_to_know_path(r), :class => "thislink card-user-profile-button hollow button primary" %>
              <% else %>
                <button type="button" class="thislink card-user-profile-button hollow button primary disabled" disabled>Edit</button>
              <% end %>

            </div>
          <%# end %>
        </div>

        <script>
          var content = "";
          my_content = document.getElementById("my_content_<%= counter %>").getAttribute("data-good_to_know");
          if(my_content != "" && my_content != null) {
            document.getElementById("my_content_<%= counter %>").innerHTML = my_content;
          }
        </script>
        <% counter = counter +1 %>

      <% end %>
    </div>

<% else %>
  <h6 align="center">No Related Entries</h6>
<% end %>

app/views/good_to_knows/edit.html.erb
<script src="//cdn.ckeditor.com/4.5.6/standard/ckeditor.js"></script>
<h2 align="center">Edit Vault Entry</h2>

<div class="row align-center">
  <%= render 'form' %>
</div>

app/views/good_to_knows/index.js.erb
$('.nav-box').css("border-top", "4px solid transparent");
$('.link').css("color", "white");
$('.link').css("text-shadow", "none");
$('.navbar-collapse').collapse("hide");
// $("#collapseBody").animate({"height" : "0"}, 250);
$('#collapseBody').promise().done(function(){
    document.getElementById('collapseBody').innerHTML = "";
    // $("#collapseBody").animate({"height" : "570"}, 700);
    $("#collapseBody").html("<%= escape_javascript(render partial: 'index', locals: { :remote => true } ) %>");
});
$('#vault').css("border-top", "4px solid #2A6C78");
$('#vault_link').css("text-shadow", "2px 2px 6px #2A6C78");

app/views/good_to_knows/new.html.erb
<h2 align="center">New Vault Entry</h2>

<div class="row align-center">
  <%= render 'form' %>
</div>

app/views/good_to_knows/search.html.erb
<%= render 'search' %>

app/views/good_to_knows/search.js.erb
$('.nav-box').css("border-top", "4px solid transparent");
$('.link').css("color", "white");
$('.link').css("text-shadow", "none");
$('.navbar-collapse').collapse("hide");
// $("#collapseBody").animate({"height" : "0"}, 250);
$('#collapseBody').promise().done(function(){
    document.getElementById('collapseBody').innerHTML = "";
    // $("#collapseBody").animate({"height" : "570"}, 700);
    $("#collapseBody").html("<%= escape_javascript(render partial: 'index2', locals: { :remote => true } ) %>");
});
$('#vault').css("border-top", "4px solid #2A6C78");
$('#vault_link').css("text-shadow", "2px 2px 6px #2A6C78");

app/views/good_to_knows/show.html.erb
<%= render :partial => 'show' %>

app/views/good_to_knows/show.js.erb
$('#vaultEntry').fadeOut("slow");
$('#vaultEntry').promise().done(function(){
  document.getElementById('vaultEntry').innerHTML = "";
  $('#vaultEntry').append("<%= escape_javascript(render(:partial => 'show', :locals => {:remote => true})) %>");
  $('#vaultEntry').fadeIn("slow");
  // $('.vaultEntry').css('box-shadow','6px 6px 10px rgba(0,0,0,.8)');
});