config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :good_to_knows do
    collection do
      get 'search'
    end
  end
  
  get 'pages/home'
  get 'pages/simple_home'
  get 'pages/profile'
  get 'pages/resume'
  get 'pages/return_home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/test'
  get 'pages/projects'
  get 'pages/inDevelopment'

  root 'pages#home'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_bootstrapStuff.html.erb
<!--Bootstrap code below -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!--Bootstrap code above -->

app/views/layouts/_myFooter.html.erb
<div style="color: #E7DFDD; background: #1D2529;">
  <div class="row align-justify" style="height: 200px;">
    <div class="column small-4 align-self-middle">
      <img class="" src="/assets/email_icon.svg" alt="email" style="width: 25px; margin-right:3px;">
      nick.schumacher07@gmail.com
    </div>
    <div class="column small-4 align-self-middle" align="right">
      <a href="https://www.facebook.com/nick.schumacher.357" style="margin-right: 5px">
        <img src="/assets/facebook_icon.svg" style="width: 30px">
      </a>
      <a href="https://github.com/nschumacher" style="margin-right: 5px">
        <img src="/assets/github_icon.svg" style="width: 30px">
      </a>
      <a href="https://www.linkedin.com/in/nicholasaschumacher" style="margin-right: 5px">
        <img src="/assets/linkedin_icon.svg" style="width: 30px;">
      </a>
			<div class="hollow button primary" style="display: inline-block; margin-bottom: 0px">
				<% if user_signed_in? %>
					<%= link_to('Logout', destroy_user_session_path, :method => :get, id: 'logout') %>
				<% else %>
					<%= link_to('Secure Access', new_user_session_path, :method => :get, id: 'sign_in') %>
				<% end %>
			</div>
    </div>

  </div>

</div>

app/views/layouts/_nav.html.erb
<div data-sticky-container id="top" data-magellan-target="top">
  <!-- <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%; background-color: #383838 !important; "> -->
  <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%;" data-top-anchor="0">
    <div class="title-bar-left">
      <ul class="horizontal menu">
        <li class="menu-text" style="" data-magellan>
          <%= image_tag("/assets/personal_logo.png", :id=>'arctis_logo', :class =>'menu')%>
          <!--<img src="/assets/personal_logo.png" id="arctis_logo" class="menu" style="">-->
          <a href="#top">Nick Schumacher</a>
        </li>
      </ul>
    </div>
    <div class="title-bar-right" style="padding-top: 18px">
      <ul class="horizontal menu" data-magellan>
        <li><a href="#first">About Me</a></li>
        <li><a href="#second">Skills</a></li>
        <li><a href="#third">Experience</a></li>
        <li><a href="#fourth">The Vault</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<!--<div class="sidenav">
  <div style="border-bottom: 1px solid #818181">
    <a href="/">
      <img src="/assets/sir_nicholas_blank.png" class="side_nav_icon" style="height: 50px; padding-left: 8px;">
    </a>
  </div>

  <div class="side_nav_icons_container">
    <!- Home ->
    <% if current_page?('/') || current_page?('/pages/home') %>
    <a href="/">
      <div id="selected" class="side_nav_icon_container" align="center">
          <img src="/assets/home_icon.png" class="side_nav_icon">
      </div>
    </a>
    <% else %>
      <a href="/">
        <div class="side_nav_icon_container" align="center">
          <img src="/assets/home_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% end %>
    <!- End Home ->
    
    <!- Profile ->
    <% if current_page?('/pages/profile') %>
      <a href="/pages/profile">
        <div class="side_nav_icon_container" align="center" id="selected">
          <img src="/assets/person_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% else %>
      <a href="/pages/profile">
        <div class="side_nav_icon_container" align="center">
          <img src="/assets/person_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% end %>
    <!- END Profile->

    <!- Resume ->
    <% if current_page?('/pages/resume') %>
      <a href="/pages/resume">
        <div class="side_nav_icon_container" align="center" id="selected">      
          <img src="/assets/resume_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% else %>
      <a href="/pages/resume">
        <div class="side_nav_icon_container" align="center">
          <img src="/assets/resume_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% end %>
    <!- End Resume ->

    <!- The Vault ->
    <% url = request.path_info %>
    <% if url.include?('/good_to_knows') %>
      <a href="/good_to_knows">
        <div class="side_nav_icon_container" align="center" id="selected">
          <img src="/assets/dev_board_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% else %>
      <a href="/good_to_knows">
        <div class="side_nav_icon_container" align="center">
          <img src="/assets/dev_board_icon.png" class="side_nav_icon">
        </div>
      </a>
    <% end %>
    <!- End The Vault ->
  </div>
</div>

<div id="top_nav">
  <a href='/'>
    <div id="top_nav_logo">
      <img src="/assets/sir_nicholas_blank.png" class="side_nav_icon" style="height: 50px; padding-left: 8px;">
    </div>
  </a>
  <div id="top_container">
    <div id="top_nav_icons_container" align="center">
      <a href="/">
        <img src="/assets/home_icon.png" class="top_nav_icon" style="">
      </a>
      <a href="/pages/profile">
          <img src="/assets/person_icon.png" class="top_nav_icon" style="">
      </a>
      <a href="/pages/resume">
          <img src="/assets/resume_icon.png" class="top_nav_icon" style="">
      </a>
      <a href="/good_to_knows">
          <img src="/assets/dev_board_icon.png" class="top_nav_icon" style="">
      </a>
    </div>
  </div>
</div>-->
<nav class="top-bar topbar-responsive" style="background: transparent;">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a href="/">
      <img src="assets/sir_nicholas_blank.png" id="arctis_logo" class="menu" style="height:25px;">
    </a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal" data-magellan>
        <li><a href="#first">Home</a></li>
        <li><a href="#second">About</a></li>
        <li><a href="#third">Skills</a></li>
        <li>
          <%= link_to '<button type="button" class="button hollow topbar-responsive-button">The Vault</button>'.html_safe, good_to_knows_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation2.html.erb
<div data-sticky-container id="top" data-magellan-target="top">
  <!-- <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%; background-color: #383838 !important; "> -->
  <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%;" data-top-anchor="0">
    <div class="title-bar-left">
      <ul class="horizontal menu">
        <li class="menu-text" style="" data-magellan>
          <!-- <img src="assets/custom_silver_sword.png" id="arctis_logo" class="menu" style=""> -->
          <a href="#top">Nick Schumacher</a>
        </li>
      </ul>
    </div>
    <div class="title-bar-right" style="padding-top: 10px">
      <ul class="horizontal menu" data-magellan>
        <li><a href="#first">About Me</a></li>
        <li><a href="#second">Projects</a></li>
        <li><a href="#third">The Vault</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navigation3.html.erb
<div data-sticky-container id="top" data-magellan-target="top">
  <!-- <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%; background-color: #383838 !important; "> -->
  <div class="title-bar sticky" data-sticky data-options="marginTop:0;" style="width:100%;" data-top-anchor="0">
    <div class="title-bar-left">
      <ul class="horizontal menu">
        <li class="menu-text" style="padding: 0px" data-magellan>
          <a href="/">
            <img src="assets/personal_logo.png" id="arctis_logo" class="menu" style="height:20px;">
          </a>
        </li>
      </ul>
    </div>
    <div class="title-bar-right" style="">
      <ul class="horizontal menu" data-magellan>
        <li><a href="/pages/home">Home</a></li>
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/projects">Skills</a></li>
        <!--<li><a href="/good_to_knows/">The Vault</a></li>-->
        <li>
          <button type="button" class="button hollow topbar-responsive-button">The Vault</button>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Sir Nicholas</title>
    <link rel="shortcut icon" type="image/x-icon" href="/assets/sir_nicholas_blank.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "application", media: "all" %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag :modernizr %>

    <script type="text/javascript">$(function(){ $(document).foundation(); });</script>
    <script type="text/javascript" scr="javascripts/jquery.raty.js"></script>
    <script type="text/javascript" scr="javascripts/ratyrate.js.erb"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>


   	<!-- Custom Font -->
    <link href="https://fonts.googleapis.com/css?family=Rajdhani|Maven+Pro|Mr+Dafoe|Megrim|Rubik" rel="stylesheet">
    <!-- Mr Dafoe for Nick signature -->
    <!-- Rubik for body -->
    <!-- Maven Pro for accent font-->
    <!-- Rajdhani for code -->
    <!-- Megrim for @sirnicholas0 -->

    <%= yield :javascript_includes %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>

    <div class="main">
      <!--<div class="content">-->
        <%= yield %>
      <!--</div>-->
    </div>

  </body>
</html>